### ISSUE TITLE
RPC method getBlock

### ISSUE THREAD

**Issue by EuroLine** [elementrem/go-elementrem#2]
Please add this method in RPC command line

**Comment by elementrem** [comment]
thank you for your interest

In web3.js, `ele_getBlock` was already enabled. But web3.js is available
only via the HttpProvider and IpcProvider.

Do you need a pure RPC command? like curl?

2016-07-12 15:15 GMT+00:00 EuroLine <notifications@github.com>:

> Please add this method in RPC command line
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elementrem/go-elementrem/issues/2>, or mute the thread
> <https://github.com/notifications/unsubscribe/ASkmymgs8XUrbC3MqajmiFI52BYxDjfyks5qU69_gaJpZM4JKgWe>
> .
>



-- 
    ©2016 Elementrem.    *http://www.elementrem.org/
<http://www.elementrem.org/>*

We are interested in your feedback.  Please let me know your thoughts.

**Comment by elementrem** [comment]
Enter the block number of getBlockByNumber in hexadecimal.
